inloco/kube-actions

dind/Dockerfile
dind/Makefile
operator/Dockerfile
operator/Makefile
operator/go.mod
operator/go.sum
runner/Dockerfile
runner/Makefile

- Operator
- Upgrade to Go 1.14
- Rewrite Dockerfile
- Rewrite Makefile
- Runner and DinD
- Support image tag schema on Dockerfile and Makefile

Update Build Configurations

---

operator/controllers/actionsrunner/reconciler.go
operator/controllers/actionsrunner/wire/collection.go

Fix error that prevented new dot files from being generated

Fix Dot Files Generation

---

operator/controllers/actionsrunner/util/converters.go
operator/controllers/actionsrunner/util/filters.go

Allow operator to properly run on a mixed runtime enviroment, such as a K8s cluster with nodes of different architectures.

Multi Runtime

---

operator/controllers/actionsrunner/facades/gh.go

Support GitHub authentication via a GitHub App private key.

GitHub App Authentication

---

dind/Makefile

- Replace `IMAGE_REPOSITORY` with `IMAGE_NAME`.
- Add `--always` to `IMAGE_VERSION`

Fix Docker Build Args on DinD

---

operator/Dockerfile
operator/Makefile

- Add compile-time variables
- Fix docker build args

Add `constants` Package to Container

---

operator/config/rbac/role.yaml
operator/controllers/actionsrunner/reconciler.go

Allow controller to operate:
- `actionsrunnerjobs`
- `configmaps`
- `secrets`
- `persistentvolumeclaims`
- `jobs`

Update RBAC Role

---

runner/Dockerfile
runner/Makefile
runner/init

- Install `python3`
- Install `pip`
- Install `docker-credential-ecr-login`
- Install `git-remote-codecommit`
- Install `skopeo`
- Set misc env vars
- Move init to `/sbin`
- Upgrade runner from `2.273.4` to `2.273.5`
- Configure git `user.name` and `user.email`
- Make Docker `credHelpers` and `plugins` params configurable via env vars

Runner Misc Upgrade

---

operator/controllers/actionsrunner/consumer.go
operator/controllers/actionsrunner/facades/gh.go
operator/controllers/actionsrunner/reconciler.go
operator/controllers/actionsrunner/watcher.go
operator/controllers/actionsrunner/wire/collection.go
operator/controllers/actionsrunner/wire/wire.go
operator/go.sum
operator/main.go

- Handle INT and TERM signals
- Delete runner on update request
- Fix error logging on Wire

Graceful Shutdown

---

runner/Dockerfile
runner/init

Export env vars containing identity information of the AWS STS caller.

AWS STS Caller Identity Enviroment Variables

---

runner/init

Fix AWS Env Vars Export

---

.github/workflows/continuous.yaml
dind/Makefile
operator/Makefile
runner/Makefile

Configure workflow to automatically build and push images to Docker Hub.

Continuous Integration and Deployment

---

runner/Dockerfile
runner/init

The region was inferred from the EC2 AZ of the current node K8s node.
EC2 Instance Metadata Query Tool was installed to retrieve the availability zone name.
https://aws.amazon.com/code/ec2-instance-metadata-query-tool/

Infer and set AWS_REGION if unset 

---

.github/workflows/codeql-analysis.yml

https://securitylab.github.com/tools/codeql

Configure CodeQL

---

operator/Dockerfile

This will allow the process to be debugged in runtime via delve.

add delve to runtime

---

Makefile

Fix https://github.com/inloco/kube-actions/actions/runs/470171047

use bash instead of dash as make shell

---

operator/controllers/actionsrunner/util/converters.go

This change will make jobs start faster.

omit imagePullPolicy on pods

---

.github/workflows/upgrade.yaml
Makefile

- Authenticate GitHub CLI
- Avoid conflict when the branch has already been created
- Set branch upstream
- Fill pull request body

Fix Continuous Upgrade

---

runner/Dockerfile

Install github/hub

---

runner/Dockerfile

Install github/cli

---

operator/api/v1alpha1/actionsrunner_types.go
operator/config/crd/bases/inloco.com.br_actionsrunnerreplicasets.yaml
operator/config/crd/bases/inloco.com.br_actionsrunners.yaml
operator/controllers/actionsrunner/util/converters.go

Make it easier to experiment with/debug runner/dind for specific jobs.

operator: allow runner/dind image override for debugging purposes

---

runner/main.go

When the runner receives a SIGTERM, it sends it to the `run.sh` process. The problem is that this process does not pass it down to its children, consequently, the workflow never has a chance to shut down gracefully.
https://github.com/actions/runner/issues/2190

Gracefully shutdown the Runner.Listener process
