inloco/kube-actions

operator/controllers/actionsrunner/wire/collection.go, operator/controllers/actionsrunner/wire/wire.go
Create a gone state that flags the wire instance as being unusable, allowing another wire for the ActionsRunner to be instantiated. This is useful when the ADO access token used by the wire is not valid anymore and another one needs to be issued.
=> Wire Gone State

operator/main.go
Set `9100` as the new default port for the Prometheus exporter.
=> Change Default Metrics Address

operator/controllers/actionsrunner/util/converters.go
- Set `RunAsUser` to `1000`
- Set `RunAsGroup` to `1000`
- Set `RunAsNonRoot` to `true`
- Set `FSGroup` to `1000`
- Mount PVC to `/root`
- Mount PVC to `/home`
=> Set PodSecurityContext

dind/daemonset.yaml
This DaemonSet registers qemu-user-static binaries on binfmt_misc to allow multi-arch Docker images to be built.
=> binfmt_misc daemonset

operator/controllers/actionsrunner/consumer.go, operator/controllers/actionsrunner/facades/ado.go, operator/controllers/actionsrunner/util/converters.go, operator/controllers/actionsrunner/watcher.go
- Sleep for 1min after job failure
- Update agentVersion to `2.273.5`
- Remap PVC mount from `/home` to `/home/user`
- Remove crun and experimental related args from runner container
- Ignore not-found error on ActionsRunnerJob deletion
=> Create Job Recovery Procedure

runner/init
This can be used to log in to Docker Hub and other registries that don't have a credential helper.
=> Configure Docker `auths` via Environment Variable

dind/Dockerfile
On November 1st, Docker Hub will start to enforce pull rate limits:
- Free plan – anonymous users: 100 pulls per 6 hours 
- Free plan – authenticated users: 200 pulls per 6 hours
- Pro plan – unlimited
- Team plan – unlimited
To reduce the impact of this change, GCR will be set as the default registry mirror for the Docker Daemon. Similar action was taken by GitLab on their CI fleet: https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/3158#note_372525803.
=> Use GCR as Registry Mirror

dind/init
The name of the binary follows the name of the go package. The package was renamed in the previous PR but I missed the init script.
=> dind: fix glue binary name

operator/controllers/actionsrunner/dot/credentials.go, operator/controllers/actionsrunner/facades/ado.go, operator/controllers/actionsrunner/util/properties.go, operator/go.mod, operator/go.sum
GitHub now requires all runners to run in FIPS mode.
https://github.com/actions/runner/pull/806
https://github.com/actions/runner/pull/896
=> Support FIPS Compliant Algorithms

operator/controllers/actionsrunner/reconciler.go, operator/controllers/actionsrunner/wire/collection.go, operator/main.go
Close wires when it is not possible to fetch its runner via K8s API. This will prevent zombie runners from acquiring locks for job consumption.
=> close wire on runner deletion

operator/controllers/actionsrunner/wire/collection.go
Detects when wires are running with an older spec of an ActionsRunner and replaces them.
=> implement wire reconciliation

operator/Makefile
For some unknown reason, the operator agent version was behind the actual runner version.
=> fix mismatching runner versions

.github/workflows/codeql-analysis.yml, .github/workflows/continuous.yaml, .github/workflows/upgrade.yaml
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
=> Workflow Dispatch

Makefile
Makefiles evaluate branch conditions upon reading the file and it was causing unexpected behaviors on the execution of the rule. This patch replaces make-branches with base-branches to solve the problem.
=> Fix Continuous Upgrade Workflow

runner/Dockerfile
From https://docs.gradle.org/current/userguide/gradle_daemon.html:
> Since Gradle 3.0, we enable Daemon by default and recommend using it for both developers' machines and Continuous Integration servers. However, if you suspect that Daemon makes your CI builds unstable, you can disable it to use a fresh runtime for each build since the runtime is completely isolated from any previous builds.
=> feat(runner): set env var to disable Gradle Daemon for Gradle-based projects

runner/Dockerfile
This will help when building the operator for multiple OS/Arch.
=> Remove OS/Arch references from AWS CLI zip name

Makefile
Upgrade workflow sometimes [fails](https://github.com/inloco/kube-actions/runs/2455603099). With this patch we can make sure the workflow won't continue if communication with Github's API fails, which is necessary to get the latest version of the runner).
=> Fix upgrade workflow

operator/controllers/actionsrunner/wire/context.go, operator/controllers/actionsrunner/wire/context_test.go
Support unmarshaling both `{"key":"value"}` and `{"key":{"t":0,"v":"value"}}` everywhere inside PipelineContextData.
```text
controller-manager-6fd6688879-hsrck manager 2022-12-19T19:53:00.950Z	ERROR	Recovering from error in wire listener	{"runner": "incognia-backend/ci-4dqbh", "error": "json: cannot unmarshal bool into Go struct field PipelineAgentJobRequest.contextData of type wire.PipelineContextData"}
controller-manager-6fd6688879-hsrck manager runtime.gopanic
controller-manager-6fd6688879-hsrck manager 	runtime/panic.go:1038
controller-manager-6fd6688879-hsrck manager github.com/inloco/kube-actions/operator/controllers/actionsrunner/wire.(*Wire).Listen.func1
controller-manager-6fd6688879-hsrck manager 	github.com/inloco/kube-actions/operator/controllers/actionsrunner/wire/wire.go:281 …
```
=> fix(operator): PipelineContextData UnmarshalJSON

dind/docker.go
This is an attempt to circumvent the occasional issues on `docker load` on "cd" runners.
=> fix(dind): don't exit on event error from dockerd, reconnect

.github/workflows/continuous.yaml, dind/Dockerfile, dind/Makefile, dind/docker.go, dind/main.go
After we changed our container runtime from docker to containerd, a new error appeared:
failed to create shim task: OCI runtime create failed: mount_setattr `/sys`: Function not implemented: unknown
This PR has 3 changes:
- Upgrade dind image 20.x.x -> 23.0.5 cause we are very far behind! This was an attempt to fix the real issue, but it didn't worked. At least we are more updated now! After I upgraded this, a new error appeared when the golang app (which ran with set-guid-to-0) tried to use iptables. The issue happens because newer versions of iptaples block this type of usage to prevent privilege-escalation (From iptables docs: iptables will exit immediately with an error code of 111 if it finds that it was called as a setuid-to-root program. iptables cannot be used safely in this …
=> Upgrade dind 20.x.x -> 23.0.5 and downgrade crun 1.18 -> 1.17.2

operator/config/crd/kustomization.yaml, operator/config/default/kustomization.yaml, operator/config/manager/manager.yaml, operator/k8s/development/kustomization.yaml, operator/k8s/production/docker-pull.daemonset.yaml, operator/k8s/production/kustomization.yaml
* As alterações de sintaxe do kustomization foram feitas pelo `kustomize edit fix`.
* O daemon-set de pre-pull foi movido do sre-cd. Isso centraliza a definição das versões no mesmo repo.
=> Kustomization refresh, add pre-pull daemon-set (moved from sre-cd)

dind/Makefile
> kube-actions[dind]: 2023/07/27 18:39:50 error from events channel: Error response from daemon: client version 1.43 is too new. Maximum supported API version is 1.42
=> dind: update docker version

dind/Dockerfile, runner/Dockerfile
Dind: crun to 1.9.0 and fuseFS to 1.13
Runner: upgrade GGCI to 5.25.0-11 and SOPS to v3.7.3
=> Upgrades on DIND and RUNNER

operator/internal/controller/actionsrunner/facades/gh.go
This is an attempt to fix the runners using expired tokens issue, based on the Github ticket response.
=> Reduce the Registration and Removal tokens ttl to 20min

runner/Dockerfile
This is for using compose as a plugin (`docker compose`), which has new features, and does not conflict with the `/usr/bin/docker-compose` binary manually installed in the Dockerfile.
=> runner: install docker-compose-plugin in image

operator/internal/controller/actionsrunner/util/converters.go
This depends on inloco/sre#674
=> Add tolatation and nodeSelector for ci nodegroup in pods
